version: '3.8'
services:
  web:
    build: . 
    ports:
      - "3000:3000" # Map host port 3000 to container port 3000
    environment:
      DATABASE_URL: postgres://username:pass@db:5432/prisma-1
      NODE_ENV: development # Set environment variables
    depends_on:
      db: 
        condition: service_healthy
    command: node ./dist/api/main.js
  db:
    image: postgres:14-alpine 
    environment:
      POSTGRES_DB: prisma-1
      POSTGRES_USER: username
      POSTGRES_PASSWORD: pass
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
  migrations:
    build: . 
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://username:pass@db:5432/prisma-1
    command: /bin/sh -c "/app/apply_migration.sh"
    profiles: ["migrations"]
